# Generated by Django 3.2 on 2021-04-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('uni_squirrel_id', models.CharField(help_text='Unique Squirrel Identification Number', max_length=255, primary_key=True, serialize=False)),
                ('latitude', models.FloatField(help_text='Latitude feature of the point')),
                ('longitude', models.FloatField(help_text='Longitude feature of the point')),
                ('shift', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Shift', max_length=255)),
                ('date', models.DateField(blank=True, help_text='Date', null=True)),
                ('age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Age is a choice between Adult and Juvenile', max_length=50, null=True)),
                ('fur_color', models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Black', 'Black'), ('Cinnamon', 'Cinnamon')], help_text='Primary Fur Color', max_length=50, null=True)),
                ('location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='Location of the squirrels', max_length=50, null=True)),
                ('specific_location', models.CharField(blank=True, help_text='Specific location of the squirrels', max_length=255, null=True)),
                ('running', models.BooleanField(help_text='If the squirrel status is running')),
                ('chasing', models.BooleanField(help_text='If the squirrel status is chasing')),
                ('climbing', models.BooleanField(help_text='If the squirrel status is climbing')),
                ('eating', models.BooleanField(help_text='If the squirrel status is eating')),
                ('foraging', models.BooleanField(help_text='If the squirrel status is foraging')),
                ('other_activities', models.CharField(blank=True, help_text='Other activities', max_length=255, null=True)),
                ('kuks', models.BooleanField(help_text='If the squirrel status was heard kuking')),
                ('quaas', models.BooleanField(help_text='If the squirrel status was heard quaaing')),
                ('moans', models.BooleanField(help_text='If the squirrel status was heard moaning')),
                ('tail_flags', models.BooleanField(help_text='If the squirrel status was flaging its tail')),
                ('tail_twitching', models.BooleanField(help_text='If the squirrel status was twitching its tail')),
                ('approaches', models.BooleanField(help_text='If the squirrel status was approaching the observer')),
                ('indifferent', models.BooleanField(help_text='If the squirrel status was indifferent to the observer')),
                ('runs_from', models.BooleanField(help_text='If the squirrel status was running from the observer')),
            ],
        ),
    ]
